export type {
  // Manifest types
  PluginLicenseType,
  PluginCategory,
  PluginSource,
  PluginCollectionColumnType,
  PluginCollectionSchema,
  PluginMigrationOperation,
  PluginMigration,
  PluginSettingOption,
  PluginSettingTestAction,
  PluginSettingDefinition,
  PluginSuggestedPrompt,
  PluginPermission,
  PluginCliEndpoint,
  PluginCronDefinition,
  PluginManifest,
  PluginSupportLinks,
  PluginRegistryEntry,
  PluginRuntimeStatus,
  // Workspace manifest block (`workspace.read` / `.write` / `.exec`)
  PluginWorkspaceCommandSlot,
  PluginWorkspaceBinding,
  PluginWorkspace,
  // Context types
  QueryOptions,
  SidebarItem,
  CliRequest,
  CliResponse,
  CliHandler,
  PluginStorage,
  PluginSecrets,
  PluginDb,
  PluginStorageStats,
  PluginSettings,
  PluginLogger,
  PluginEvents,
  PluginSessions,
  SessionStatus,
  SessionPendingAction,
  SessionMessage,
  PluginAi,
  PluginAiStructuredRequest,
  PluginFs,
  PluginHttp,
  PluginCron,
  PluginCli,
  PluginSidebar,
  PluginToast,
  PluginContext,
  PluginAuthUser,
  PluginAuthSession,
  PluginAuth,
  InboxItem,
  PluginInbox,
  RecordingStartResult,
  RecordingStopResult,
  Recording,
  PluginRecording,
  // Text to speech (`tts`)
  SynthesizedSpeech,
  PluginTts,
  // Session history (`sessions.readHistory`)
  HistoryProject,
  HistorySession,
  HistoryMessage,
  HistoryGrantResult,
  PluginSessionHistory,
  // Firebase (`firebase`)
  FirebaseAccount,
  FirebaseProject,
  FirebaseSetupStatus,
  PluginFirebase,
  // Spend reporting (`spend`)
  SpendWindow,
  SpendEngineLine,
  SpendFeatureLine,
  SpendCharge,
  SpendReportBreakdown,
  PluginSpend,
  // Workspace (`workspace.read` / `.write` / `.exec`)
  WorktreeRef,
  WorktreeStatus,
  WorktreeInfo,
  WorkspaceScope,
  WorkspaceHandle,
  WorkspaceEntry,
  WorkspaceCheckout,
  WorkspaceGlobOpts,
  WorkspaceProjectRef,
  WorkspaceWriteFilesResult,
  WorkspaceExecResult,
  WorkspaceRunRequest,
  // The exec JOB path (`exec` / `execStatus` / `execResults` / `execCancel`)
  WorkspaceExecJobState,
  WorkspaceExecStartRequest,
  WorkspaceExecStartResult,
  WorkspaceExecJobStatus,
  WorkspaceExecPollRequest,
  WorkspaceExecPollResponse,
  WorkspaceApi,
  // Backend types
  PluginBackend,
  PluginActivate,
} from './types/index.js'

// Validators (runtime value exports)
export { manifestSchema, validateManifest, PLUGIN_PERMISSIONS } from './validators/manifest.js'
export type { ManifestValidationResult } from './validators/manifest.js'

// Tool-activity transcript markers (runtime value exports). Import these rather
// than hardcoding the glyphs - see the module for provenance and codepoints.
export {
  TOOL_CALL_MARKER,
  TOOL_RESULT_MARKER,
  TOOL_CALL_RE,
  TOOL_RESULT_RE,
  stripToolLines,
} from './types/markers.js'
